### PR TITLE
expose probabilities for probabilistic transitions

### PR DESCRIPTION
**Pull request by ronuchit**

### CODE REVIEW

**Comment by GCrispino** [comment]
@ronuchit, this looks like what I was thinking! I didn't get the total_proba calculation at first, but it should be done because since new literals may come from different effects and probabilities for a specific new state. Is that it?

**Comment by ronuchit** [comment]
Yeah, I'm just multiplying the probabilities of each literal in the itertools.product. Hopefully it makes sense...

If you'd like, it might be useful to add a more comprehensive test for these probabilities (with another domain file that has several probabilistic effects in one operator), to ensure that the code is behaving correctly. Let me know if you're interested in  doing this. Otherwise, I'm also happy to just merge this in if you want to start using it immediately.

**Comment by GCrispino** [comment]
> Yeah, I'm just multiplying the probabilities of each literal in the itertools.product. Hopefully it makes sense...

It does for me :)

> If you'd like, it might be useful to add a more comprehensive test for these probabilities (with another domain file that has several probabilistic effects in one operator), to ensure that the code is behaving correctly. Let me know if you're interested in doing this. Otherwise, I'm also happy to just merge this in if you want to start using it immediately.

I could do this, yes. Can you merge this PR, so I can use this new feature and then create a new PR with the new test?

**Comment by ronuchit** [comment]
Done!

**Comment by GCrispino** [comment]
Thanks!!

**Pull request merged**
