### PR TITLE
Add Navigation domains

### PR DESCRIPTION
**Pull request by GCrispino**
This PR adds Navigation's 10 domains from IPPC2011 to PDDLGym, with a render function adapted from Sokoban's one.
The PDDL files were based on the ones that can be found on the [IPPC2011 official website](http://users.cecs.anu.edu.au/~ssanner/IPPC_2011/) (here is the link to the zip file containing the domain files: [link](http://users.cecs.anu.edu.au/~ssanner/IPPC_2011/final_competition_42311.zip)).

The original PDDL filess from which this PR is based upon use the `when` keyword and rewards (here is an example of the original PDDL version of the 4th domain: [link](https://gist.github.com/GCrispino/5462db0419ded81d0bf13df8a86d188a)). The former is replaced by using a predicate with the format `is-col-x`, where `x` is an index to the column in the grid; the latter is simply ignored.

There are multiple domains instead of just one because in this PDDL definition, the probabilities of each instance of Navigation are hardcoded into the domain definition, requiring 1 domain definition per instance, what makes a total of 10 domains.
I don't know if there's a better way to do this in PDDL or PDDLGym. In RDDL, for example, this can be easily circumvented with float non-fluents.

I'd understand if adding 10 domains in this way is maybe not desired by the maintainers, so feel free to comment upon this.
However, I still think this is worth adding because it's a domain from a planning competition, which might be useful for researchers using PDDLGym.

### CODE REVIEW

**Comment by ronuchit** [comment]
Thank you Gabriel! We don't really have any issues with more domains being added to PDDLGym! So just so I understand, the only difference among the 10 domains is the probability values for the stochastic effects?

**Comment by GCrispino** [comment]
Hey @ronuchit :). The differences are the probabilities and also the grid sizes. The first domain is 3x4 while the 10th is 5x20.

**Comment by ronuchit** [comment]
Thanks! LGTM

**Comment by GCrispino** [comment]
Thanks!

**Pull request merged**
