### PR TITLE
Expblocks render

### PR DESCRIPTION
**Pull request by GCrispino**
Hi!

This PR adds rendering to the Exploding Blocksworld domain (`PDDLEnv-Explodingblocksworld-v0`).
For now I've simply copied the rendering function from Blocksworld and added a drawing of a cross to blocks that are destroyed.
It still needs some kind of feedback for when the table is destroyed. Not sure if I add a drawing of a big cross on the table or add some text at the top saying "Table is (not) destroyed" like in the Tireworld rendering.
Any comments or ideas?

Here's a rendering for a state of problem5 (in this case, the green block is the single one that's destroyed):

frame7

### CODE REVIEW

**Comment by ronuchit** [comment]
Great! Maybe just a cross on the table would be sufficient, or text at the top would work too, whatever you find easier and/or more visually appealing.

**Comment by GCrispino** [comment]
> Great! Maybe just a cross on the table would be sufficient, or text at the top would work too, whatever you find easier and/or more visually appealing.

Sure! I could easily add a cross with the same size as the blocks one to the table. Would that work?

**Comment by ronuchit** [comment]
Yes!

**Comment by GCrispino** [comment]
> Yes!

Ok! I'll add that when I can. Thanks!

**Comment by GCrispino** [comment]
Done!

**Comment by ronuchit** [comment]
Thanks, merged it in!

**Pull request merged**
