### PR TITLE
Various Depreciation/Bug Fixes

### PR DESCRIPTION
**Pull request by mplemay**
# Overview
The `Hello, PDDLGym` example in the readme was broken on the master branch. This PR introduces some fixes for a couple of bugs, silences OpenAI gym related depreciation notices, and address a pillow depreciation notice.

# Disclaimer
This PR was only tested on my machine with the most recent dependencies. There is a possibility that conforming to the most recent (or relatively recent) dependencies breaks other python environment configurations.

## Python Version
`Python 3.9.13`

## Dependencies
```
cloudpickle==2.1.0
cycler==0.11.0
fonttools==4.33.3
gym==0.24.1
gym-notices==0.0.7
imageio==2.19.3
importlib-metadata==4.11.4
kiwisolver==1.4.3
matplotlib==3.5.2
networkx==2.8.4
numpy==1.22.4
packaging==21.3
Pillow==9.1.1
pyparsing==3.0.9
python-dateutil==2.8.2
PyWavelets==1.3.0
scikit-image==0.19.3
scipy==1.8.1
six==1.16.0
tifffile==2022.5.4
zipp==3.8.0
```

### CODE REVIEW

**Comment by tomsilver** [comment]
Thank you so much!

The `gym` change looks good, thank you for bringing us up to date. Would you mind also updating the requirements.txt file:
```
gym>=0.24.0
```

I am having trouble with the PIL change on Python 3.6.7 with the latest version of Pillow available for that version of Python (8.4.0). When running your change, I hit this:
```
AttributeError: module 'PIL.Image' has no attribute 'Resampling'
```

Could you clarify the issue that led to those changes? Does the current code crash in your setting or is there a subtle bug?

**Comment by mplemay** [comment]
> The `gym` change looks good, thank you for bringing us up to date. Would you mind also updating the requirements.txt file:
> 
> ```
> gym>=0.24.0
> ```

Can do!

> Could you clarify the issue that led to those changes? Does the current code crash in your setting or is there a subtle bug?
It looks like in pillow 9 they added the following depreciated message:
```
/Users/matthewlemay/Github/pddlgym/pddlgym/rendering/utils.py:76: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  im = im.resize((new_width, new_height),  Image.ANTIALIAS)
```
There are a couple of options to fix this:
* The version could be pegged to `pillow<9` to avoid the depreciation notice.
* The notice can be ignored and the requirement can be set to `pillow>=8, <10`
* Python 3.6 can be depreciated

Let me know what works best!

**Comment by tomsilver** [comment]
Ah got it, thanks for the additional information. Let's go with your second option:

>The notice can be ignored and the requirement can be set to pillow>=8, <10

Thank you again!

**Comment by mplemay** [comment]
Also, it is worth noting that setting `disable_env_checker=True` silences some depreciation (ex: env.seed depreciated in favor of env.reset(seed=seed), etc.) warnings and an error caused by `LiteralSetSpace`  not having a `contains` method. Once I get some more bandwidth, I will look into those.

**Comment by mplemay** [comment]
Everything should now be good to go. Thank you for going out of your way to merge handle these changes!

**Comment by tomsilver** [comment]
Of course, thank you for making it easy!

Confirmed that the changes work with my setup on 3.6.7 too.

**Pull request merged**
