### PR TITLE
Use pyperplan heuristic without reparsing pddl multiple times

### PR DESCRIPTION
**Pull request by gehring**

### CODE REVIEW

**Comment by ronuchit** [comment]
There's some repeated lines in def step() and def sample_transition(), in the "if self._shape_reward_mode:" block. Maybe factor that out into a new method, so that in case we ever want to change how we compute the intrinsic reward, we only have to change it in one place.

Otherwise LGTM.

**Comment by gehring** [comment]
@ronuchit Unfortunately, there is a lot of almost identical code between those two methods, not just those two lines. I wanted to avoid this when I originally wrote `env.sample_transition(...)` but it required more refactoring than I was willing to do at the time.

You'll notice that when implementing `env.sample_transition(...)`, I chose to not use `env._get_debug_info()` for the important reason that it and the methods it calls have a lot of dependencies on the internal state of the environment. I didn't quite feel comfortable enough with code to disentangle `env._state` from those methods.

That being said, I can give it a 2nd go and try to properly refactor out unnecessary dependencies to `env._state`. If I mange that, then we could implement `env.step(...)` as a lean wrapper around `env.sample_transition(...)`.

**Comment by gehring** [comment]
@ronuchit @tomsilver Just merged in the state refactor. Let me know if you'd like me to change anything.

**Comment by gehring** [comment]
Reworked and merged in #29

**Pull request closed without merging**
