### PR TITLE
Fix bugs in _apply_effects and add test for probabilistic domains

### PR DESCRIPTION
**Pull request by GCrispino**
Hello!

This PR fixes bugs related to correctly calculating states' probabilities, and adds a new test (with a new test domain) for domains with actions that have multiple probabilistic effects.

I'm thinking of adding one more test to test domains with actions that have a single probabilistic effect, but with multiple probabilities (such as `traverse-rocks` in the River domain), too.

### CODE REVIEW

**Comment by ronuchit** [comment]
Thank you for looking into this in more detail & fixing the bugs, Gabriel! That extra test you're suggesting sounds good. Let's merge after you add it in.

**Comment by GCrispino** [comment]
No problem, Rohan!
I've just added the new test. Please check it out to see if the new domain and the new tests are fine or are getting too repetitive :)

**Comment by ronuchit** [comment]
Thanks! Tests can never be too repetitive ;) will merge this in now.

**Comment by GCrispino** [comment]
> Thanks! Tests can never be too repetitive ;) will merge this in now.

Cool, thanks!

**Pull request merged**
